main: eu.minespot.life_and_death.Main
name: LifeAndDeath
version: 0.0.1
author: MinespotDevs
description: A plugin implementing human lifecycle in Minecraft.
commands:
  lifeanddeath:
    aliases: [lad, ld]
    description: The default command.