main: eu.minespot.life_and_death.Main
name: LifeAndDeath
version: 0.0.1
author: MinespotDevs
description: A plugin implementing human lifecycle in Minecraft.
commands:
  ld:
    description: The default command
    usage: /ld